/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifsc.navegacaoderobos;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Fernando
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    int i;
    int j;
    Nodo[][] nodo;

    public TelaInicial() {
        reset();

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldInicialX = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldInicialY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldFinalX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldFinalY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldParedeInicialX = new javax.swing.JTextField();
        jTextFieldParedeInicialY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldParedeFinalX = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldParedeFinalY = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton5Passos = new javax.swing.JButton();
        jButton10Passos = new javax.swing.JButton();
        jButton15Passos = new javax.swing.JButton();
        jButton25Passos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Coordenada Inicial  X:");

        jLabel2.setText("Y:");

        jLabel3.setText("Coordenada Final   X:");

        jLabel4.setText("Y:");

        jLabel5.setText("Adicionar Parede");

        jLabel6.setText("Coordenada Inicial  X:");

        jLabel7.setText("Y:");

        jLabel8.setText("Coordenada Final   X:");

        jLabel9.setText("Y:");

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Busca Bidirecional", "Busca A*", "Busca de Custo Uniforme" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel10.setText("Exemplos");

        jButton5Passos.setText("5 Passos");
        jButton5Passos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5PassosActionPerformed(evt);
            }
        });

        jButton10Passos.setText("10 Passos");
        jButton10Passos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10PassosActionPerformed(evt);
            }
        });

        jButton15Passos.setText("15 Passos");
        jButton15Passos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15PassosActionPerformed(evt);
            }
        });

        jButton25Passos.setText("25 Passos");
        jButton25Passos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton25PassosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldInicialX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInicialY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldFinalX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldFinalY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldParedeInicialX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldParedeInicialY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldParedeFinalX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldParedeFinalY, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAdicionar)
                            .addComponent(jButtonBuscar)))
                    .addComponent(jLabel10))
                .addContainerGap(186, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton5Passos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10Passos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15Passos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton25Passos)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldInicialX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldInicialY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldFinalX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldFinalY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldParedeInicialX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldParedeInicialY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldParedeFinalX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldParedeFinalY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAdicionar))
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5Passos)
                    .addComponent(jButton10Passos)
                    .addComponent(jButton15Passos)
                    .addComponent(jButton25Passos))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:

        nodo[Integer.parseInt(jTextFieldInicialY.getText())][Integer.parseInt(jTextFieldInicialX.getText())].setSaida(Boolean.TRUE);
        nodo[Integer.parseInt(jTextFieldFinalY.getText())][Integer.parseInt(jTextFieldFinalX.getText())].setChegada(Boolean.TRUE);

        if (jComboBox1.getSelectedIndex() == 0) {
            BuscaBidirecional busca = new BuscaBidirecional();

            long tempoInicial = System.currentTimeMillis();

            String r = busca.buscar(nodo);
            tempoInicial = (System.currentTimeMillis() - tempoInicial);
            int visitado = 0;
            //int explorado = 0;
            for (i = 1; i < 51; i++) {
                for (j = 1; j < 51; j++) {

                    if (nodo[i][j].getEstado()) {

                    } else if (nodo[i][j].getChegada()) {
                        visitado++;
                    } else if (nodo[i][j].getSaida()) {
                        visitado++;
                    } else if (nodo[i][j].getResultado()) {
                        visitado++;
                    } else if (nodo[i][j].getVisitadoA()) {
                        visitado++;
                    } else if (nodo[i][j].getVisitadoB()) {
                        visitado++;

                    }

                }
            }

            JOptionPane.showMessageDialog(null, "O tempo foi " + tempoInicial + " Milisegundos\n"
                    + "Nos visitados: " + visitado);

            String[] res = r.split(";");
            for (int f = 0; f < res.length; f = f + 2) {
                nodo[Integer.parseInt(res[f])][Integer.parseInt(res[f + 1])].setResultado(Boolean.TRUE);
            }
            Tela tela = new Tela(nodo);
            tela.setVisible(true);
            reset();

        } else if (jComboBox1.getSelectedIndex() == 1) {
            BuscaAEstrela busca = new BuscaAEstrela();

            long tempoInicial = System.currentTimeMillis();
            String r = busca.buscar(nodo);
            tempoInicial = (System.currentTimeMillis() - tempoInicial);
            int visitado = 0;
            int explorado = 0;
            for (i = 1; i < 51; i++) {
                for (j = 1; j < 51; j++) {

                    if (nodo[i][j].getEstado()) {

                    } else if (nodo[i][j].getChegada()) {

                    } else if (nodo[i][j].getSaida()) {
                        visitado++;
                        explorado++;
                    } else if (nodo[i][j].getResultado()) {
                        visitado++;
                        explorado++;
                    } else if (nodo[i][j].getVisitadoB()) {
                        visitado++;
                        explorado++;
                    } else if (nodo[i][j].getVisitadoA()) {
                        visitado++;
                    }

                }
            }

            JOptionPane.showMessageDialog(null, "O tempo foi " + tempoInicial + " Milisegundos\n"
                    + "Nos explorados: " + explorado + "\n"
                    + "Nos visitados: " + visitado);

            String[] res = r.split(";");
            for (int f = 0; f < res.length; f = f + 2) {
                nodo[Integer.parseInt(res[f])][Integer.parseInt(res[f + 1])].setResultado(Boolean.TRUE);
            }
            Tela tela = new Tela(nodo);
            tela.setVisible(true);

            reset();
        } else if (jComboBox1.getSelectedIndex() == 2) {
            BuscaUniforme busca = new BuscaUniforme();

            long tempoInicial = System.currentTimeMillis();

            String r = busca.buscar(nodo);
            tempoInicial = (System.currentTimeMillis() - tempoInicial);
            int visitado = 0;
            //int explorado = 0;
            for (i = 1; i < 51; i++) {
                for (j = 1; j < 51; j++) {

                    if (nodo[i][j].getEstado()) {

                    } else if (nodo[i][j].getChegada()) {
                        visitado++;
                    } else if (nodo[i][j].getSaida()) {
                        visitado++;
                    } else if (nodo[i][j].getResultado()) {
                        visitado++;
                    } else if (nodo[i][j].getVisitadoA()) {
                        visitado++;
                    } else if (nodo[i][j].getVisitadoB()) {
                        visitado++;

                    }

                }
            }

            JOptionPane.showMessageDialog(null, "O tempo foi " + tempoInicial + " Milisegundos\n"
                    + "Nos visitados: " + visitado);

            String[] res = r.split(";");
            for (int f = 0; f < res.length; f = f + 2) {
                nodo[Integer.parseInt(res[f])][Integer.parseInt(res[f + 1])].setResultado(Boolean.TRUE);
            }
            Tela tela = new Tela(nodo);
            tela.setVisible(true);

            reset();
        } else {

        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        // TODO add your handling code here:
        for (int i = Integer.parseInt(jTextFieldParedeInicialY.getText()); i <= Integer.parseInt(jTextFieldParedeFinalY.getText()); i++) {
            for (int j = Integer.parseInt(jTextFieldParedeInicialX.getText()); j <= Integer.parseInt(jTextFieldParedeFinalX.getText()); j++) {
                nodo[i][j].setEstado(true);
            }
        }
        jTextFieldParedeInicialY.setText("");
        jTextFieldParedeInicialX.setText("");
        jTextFieldParedeFinalX.setText("");
        jTextFieldParedeFinalY.setText("");
        jTextFieldParedeInicialY.requestFocus();
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButton5PassosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5PassosActionPerformed
        // TODO add your handling code here:
        jTextFieldInicialX.setText("14");
        jTextFieldInicialY.setText("9");
        jTextFieldFinalX.setText("19");
        jTextFieldFinalY.setText("10");
        jButtonBuscar.doClick();
    }//GEN-LAST:event_jButton5PassosActionPerformed

    private void jButton10PassosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10PassosActionPerformed
        // TODO add your handling code here:
        jTextFieldInicialX.setText("14");
        jTextFieldInicialY.setText("9");
        jTextFieldFinalX.setText("22");
        jTextFieldFinalY.setText("12");
        for (int i = 7; i <= 14; i++) {
            nodo[i][18].setEstado(true);
        }
        jButtonBuscar.doClick();
    }//GEN-LAST:event_jButton10PassosActionPerformed

    private void jButton15PassosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15PassosActionPerformed
        // TODO add your handling code here:
        jTextFieldInicialX.setText("20");
        jTextFieldInicialY.setText("3");
        jTextFieldFinalX.setText("13");
        jTextFieldFinalY.setText("18");
        jButtonBuscar.doClick();
    }//GEN-LAST:event_jButton15PassosActionPerformed

    private void jButton25PassosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton25PassosActionPerformed
        // TODO add your handling code here:
        jTextFieldInicialX.setText("46");
        jTextFieldInicialY.setText("8");
        jTextFieldFinalX.setText("21");
        jTextFieldFinalY.setText("21");
        for (int g = 17; g <= 22; g++) {
            nodo[g][23].setEstado(true);
        }
        for (int g = 33; g <= 38; g++) {
            nodo[8][g].setEstado(true);
        }
        for (int g = 11; g <= 14; g++) {
            for (int h = 30; h <= 33; h++) {
                nodo[g][h].setEstado(true);
            }
        }
        for (int g = 24; g <= 26; g++) {
            for (int h = 18; h <= 20; h++) {
                nodo[g][h].setEstado(true);
            }
        }
        jButtonBuscar.doClick();
    }//GEN-LAST:event_jButton25PassosActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed
    public void reset() {

        nodo = new Nodo[55][55];
        for (i = 1; i < 51; i++) {
            for (j = 1; j < 51; j++) {
                nodo[i][j] = new Nodo(i, j);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10Passos;
    private javax.swing.JButton jButton15Passos;
    private javax.swing.JButton jButton25Passos;
    private javax.swing.JButton jButton5Passos;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextFieldFinalX;
    private javax.swing.JTextField jTextFieldFinalY;
    private javax.swing.JTextField jTextFieldInicialX;
    private javax.swing.JTextField jTextFieldInicialY;
    private javax.swing.JTextField jTextFieldParedeFinalX;
    private javax.swing.JTextField jTextFieldParedeFinalY;
    private javax.swing.JTextField jTextFieldParedeInicialX;
    private javax.swing.JTextField jTextFieldParedeInicialY;
    // End of variables declaration//GEN-END:variables
}
